apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bhjg7kmrc-nodejs 
  janus-idp.io/tekton: bhjg7kmrc-nodejs
  backstage.io/kubernetes-id: bhjg7kmrc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bhjg7kmrc-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  