apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bhjg7kmrc-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b58137d7c1.92a9.p3.openshiftapps.com/rhtap/rhtap-qe:1027111db28661e30d6c1dbaab8b37ca143fe340@sha256:9421181a4f749ee5e370ca1ddcdfe443a6d80ff0c174d608993ca727e9885023
          name: container-image
