apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bhjg7kmrc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bhjg7kmrc-nodejs 
  name: bhjg7kmrc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bhjg7kmrc-nodejs 
